nombre = input("¿Cuál es su nombre?:")
print(f"Bienvenido {nombre} a este nuevo mundo :)")
edad = int(input("¿Cuál es su edad?:"))
print(f"Su edad x2 es: {edad*2}")
primer_numero = int(input("Dame un número entero:"))
segundo_numero = int(input("Dame otro número entero:"))
print(f"La suma y su resultado es: {primer_numero + segundo_numero}")
numero_decimal = float(input("Dame un número decimal:"))
print(f"La mitad de eso es: {numero_decimal / 2}")
anie_actual = 2025
anie_usuario = int(input("¿Cuál es su año de nacimiento?:"))
print(f"Su edad es: {anie_actual - anie_usuario} años")
precio_producto = float(input("Dame el precio de un producto:"))
numero_unidades = int(input("Dame el número de unidades de ese producto:"))
print(f"Su total a pagar es de:${precio_producto*numero_unidades}")
numero_cuadrado = int(input("Dame un número entero: "))
print(f"Ese número al cuadrado es:{numero_cuadrado**2}")
numero1 = int(input("Dame un número:"))
numero2 = int(input("Dame otro número:"))
print(f"El promedio de ese número es: {(numero1 + numero2)/2}")
nombre_completo = input("Dame tu nombre completo: ")
edad_usuario = input("Dame ahora tu edad: ")
print(f"Hola, {nombre_completo}. Tienes {edad_usuario} años.")